name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Set up Docker
        uses: docker/setup-buildx-action@v4

      - name: Build image
        run: docker build -t events-api .

      - name: Start container
        run: docker run -d -p 5000:5000 --name events-api-container events-api

      - name: Wait for API
        run: |
            for i in {1..30}; do
              if curl --fail http://localhost:5000/api/events; then
                echo "API is ready"
                exit 0
              fi
            
              echo "Waiting for API..."
              sleep 2
            done
            
            echo "API did not start"
            docker logs events-api-container
            exit 1  

      - name: Set Up Python in Runner
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: Install requirements
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run tests
        run: pytest
